- name: yum update
  yum: name=* state=latest

- name: disable iptables
  service: name=firewalld state=stopped enabled=no

- name: install repositorys
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "http://rpms.famillecollet.com/enterprise/remi-release-7.rpm"
    - epel-release 

- name: install common packages
  yum: name={{ item  }} state=latest
  with_items:
    - libselinux-python
    - man
    - git
    - vim

- name: remove localtime
  file: path=/etc/localtime state=absent

- name: change timezone
  file: src=/usr/share/zoneinfo/Asia/Tokyo dest=/etc/localtime state=link force=yes mode=0644

- name: change locale
  lineinfile: >-
    dest=/etc/locale.conf
    state=present
    regexp=^LANG=
    line='LANG="ja_JP.UTF-8"'
