- name: install gd-last
  yum: name=gd-last enablerepo=remi state=latest

- name: install php
  yum: name={{item}} enablerepo=remi-php56 state=present
  with_items:
    - php
    - php-common
    - php-pdo
    - php-cli
    - php-devel
    - php-mysqlnd
    - php-mbstring
    - php-gd
    - php-intl
    - php-xml

- name: copy php.ini
  copy: src=php.ini dest=/etc/php.ini backup=yes
